= Protokoll 2020-10-31
Simon Zweimüller
1.0, 2020-10-31
:icons: font

== Organisatorisches

.Teilnehmer
|===
|Teilnehmer

|Simon Ittensammer

|Simon Zweimüller

|===

== Themen

* Validation for new Room
* refactor userValue and roomValue to Observables
* Improve data clearance on logout
* Move play-song logic to the control-bar
* Change Layout of Room
* Change Layout of Your-Profile and Your-Friends

== Arbeit & Erkenntnisse

Verhindert das erstellen von Rooms ohne Namen. Nach dem erstellen wird man nun direkt auf die Roomlist zurückgeleitet.

Der User und der aktuelle Room sind nun über Observables von überall im Angular abrufbar.
Dies erleichtert die Frontend-Programmierung massiv, da man nun sich kaum noch mit der Übergabe von Parametern herumschlagen muss.

Wenn sich ein User ausloggt werden nun sämtliche Daten erfolgreich aus dem lokalen Speicher gelöscht.

Das abspielen der Lieder wird nun im control-bar-component und nicht mehr im room-component verwaltet.
Dadurch wird die Musik immer abgespielt, egal wo man sich innerhalb der Applikation befindet.

Der Room-Component ist auf 2 verschiedene Hälften aufgeteilt.
Links befinden sich Infos über den Room wie die Mitgliederliste und die Playlist und rechts befindet sich ein Chat.

Der Profile- und der Friend-Component wurden auf eine Seite zusammengefasst.
Links befinden sich nun Infos zum Profil und rechts die Freundschaftsanfragen und die Freundesliste.

Alle diser Listen können auf- und zugeklappt werden um Platz zu sparen.
Auch können diese gescrollt werden um alle Infos anzeigen zu können.

== Links
